/* The API. Small on purpose: episodes, a summary, accounts, one migration
 * endpoint and aggregate admin metrics. Nothing else. */

import * as repo from './repo.js';
import * as auth from './auth.js';
import { adminMetrics } from './metrics.js';
import { validateCredentials } from './validate.js';
import { sendVerification, canSend } from './email.js';
import { config } from './config.js';
import { dbStatus } from './db.js';
import { badRequest, forbidden, notFound, unauthorised } from './util.js';
import { summaryText } from '../js/summary.js';
import { DOMAINS } from '../js/registry.js';

/** Issues a token and emails the link. Silent when email is not configured. */
async function offerVerification(user, origin) {
  const token = await auth.issueEmailToken(user.id, 'verify');
  const base = config.email.publicUrl || origin || '';
  await sendVerification({
    to: user.email,
    name: user.name,
    url: `${base}/verify?token=${encodeURIComponent(token)}`
  });
}

/** Adapter so the shared summary generator can read from the database. */
const dbSource = (entries) => ({
  isEmpty: () => entries.length === 0,
  all: (type) => (type ? entries.filter((e) => e.type === type) : entries)
});

const ok = (body, extra = {}) => ({ status: 200, body, ...extra });

export const routes = [
  /* ── Health check: liveness only, no data, no auth ── */
  {
    method: 'GET',
    path: '/api/health',
    auth: false,
    handler: async () => ok({ status: 'ok', database: (await dbStatus()).ok ? 'ok' : 'error', time: new Date().toISOString() })
  },

  /* ── Accounts ── */
  {
    method: 'POST',
    path: '/api/auth/signup',
    auth: false,
    handler: async ({ body, ip, origin }) => {
      auth.throttle(`signup:${ip}`, { limit: 10, windowMs: 60 * 60 * 1000 });
      const creds = validateCredentials(body, { requireName: true, requireTerms: true });
      const user = await auth.createUser(creds);
      const { token, expires } = await auth.createSession(user.id);
      // A failed send must never cost someone their account.
      await offerVerification(user, origin).catch(() => {});
      return ok({ user, verificationSent: canSend() }, { cookie: auth.sessionCookie(token, expires) });
    }
  },
  {
    method: 'POST',
    path: '/api/auth/login',
    auth: false,
    handler: async ({ body, ip }) => {
      auth.throttle(`login:${ip}`);
      const user = await auth.authenticate(body?.email, body?.password);
      auth.resetThrottle(`login:${ip}`);
      const { token, expires } = await auth.createSession(user.id);
      return ok({ user }, { cookie: auth.sessionCookie(token, expires) });
    }
  },
  {
    method: 'POST',
    path: '/api/auth/logout',
    auth: false,
    handler: async ({ token }) => {
      await auth.destroySession(token);
      return ok({ ok: true }, { cookie: auth.clearCookie() });
    }
  },
  {
    method: 'GET',
    path: '/api/auth/me',
    auth: false,
    handler: ({ user }) => ok({ user: user || null })
  },

  {
    method: 'POST',
    path: '/api/auth/verify',
    auth: false,
    handler: async ({ body }) => {
      const userId = await auth.consumeEmailToken(String(body?.token || ''), 'verify');
      const user = await auth.markEmailVerified(userId);
      return ok({ user });
    }
  },
  {
    method: 'POST',
    path: '/api/auth/resend-verification',
    auth: true,
    handler: async ({ user, ip, origin }) => {
      auth.throttle(`verify:${ip}`, { limit: 5, windowMs: 60 * 60 * 1000 });
      if (user.emailVerified) return ok({ alreadyVerified: true });
      await offerVerification(user, origin);
      return ok({ sent: canSend() });
    }
  },

  /* ── Episodes ── */
  {
    method: 'GET',
    path: '/api/episodes',
    auth: true,
    handler: async ({ user, query }) => {
      const type = query.get('type');
      if (type && !DOMAINS.some((d) => d.type === type)) throw badRequest('Unknown type.');
      return ok({ episodes: await repo.listEntries(user.id, type || undefined) });
    }
  },
  {
    method: 'POST',
    path: '/api/episodes',
    auth: true,
    handler: async ({ user, body }) => ({ status: 201, body: { episode: await repo.createEntry(user.id, body) } })
  },
  {
    method: 'GET',
    path: '/api/episodes/:id',
    auth: true,
    handler: async ({ user, params }) => {
      const episode = await repo.getEntry(user.id, params.id);
      if (!episode) throw notFound('That episode is not in your record.');
      return ok({ episode });
    }
  },
  {
    method: 'PATCH',
    path: '/api/episodes/:id',
    auth: true,
    handler: async ({ user, params, body }) => ok({ episode: await repo.updateEntry(user.id, params.id, body) })
  },
  {
    method: 'DELETE',
    path: '/api/episodes/:id',
    auth: true,
    handler: async ({ user, params }) => {
      await repo.deleteEntry(user.id, params.id);
      return ok({ ok: true });
    }
  },

  /* ── The doctor summary, generated by the same code the phone runs ── */
  {
    method: 'GET',
    path: '/api/summary',
    auth: true,
    handler: async ({ user }) => {
      const entries = await repo.listEntries(user.id);
      return ok({ summary: summaryText(dbSource(entries)), episodes: entries.length });
    }
  },

  /* ── Migration from a device (Phase 5) ── */
  {
    method: 'POST',
    path: '/api/migrate',
    auth: true,
    handler: async ({ user, body }) => {
      const entries = Array.isArray(body?.entries) ? body.entries : null;
      if (!entries) throw badRequest('Expected { entries: [...] }.');
      if (entries.length > 2000) throw badRequest('That is more entries than this prototype imports at once.');
      // All or nothing — a rejected entry leaves the account untouched.
      const report = await repo.importEntries(user.id, entries);
      return ok({ ...report, total: await repo.countEntries(user.id) });
    }
  },

  /* ── Admin: aggregate counters only ── */
  {
    method: 'GET',
    path: '/api/admin/metrics',
    auth: true,
    handler: async ({ user }) => {
      if (user.role !== 'admin') throw forbidden('Admin access only.');
      return ok(await adminMetrics());
    }
  }
];

/** Matches a path against the table, filling :params. */
export function matchRoute(method, path) {
  for (const route of routes) {
    if (route.method !== method) continue;
    const a = route.path.split('/');
    const b = path.split('/');
    if (a.length !== b.length) continue;

    const params = {};
    let hit = true;
    for (let i = 0; i < a.length; i++) {
      if (a[i].startsWith(':')) params[a[i].slice(1)] = decodeURIComponent(b[i]);
      else if (a[i] !== b[i]) { hit = false; break; }
    }
    if (hit) return { route, params };
  }
  // Path exists under another method?
  if (routes.some((r) => r.path.split('/').length === path.split('/').length)) return null;
  return null;
}

export { unauthorised };
